name: glassmorphism_ui
description: A Flutter package that provides a glass (frosted) effect UI container. You can use it your apps.
version: 1.0.0
homepage: https://example.com

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true